xcode_project: Travis.xcodeproj
xcode_scheme: Travis
xcode_sdk: iphonesimulator12.1
osx_image: xcode10.1
language: swift
install:
 - bundle install
 - bundle update
script:
   - fastlane hello
   - xcodebuild clean test -project "$TRAVIS_XCODE_PROJECT" -scheme "$TRAVIS_XCODE_SCHEME" -sdk "$TRAVIS_XCODE_SDK" -destination "platform=iOS Simulator,OS=latest,name=iPhone 7" CODE_SIGN_IDENTITY=“” CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet
