xcode_project: Travis.xcodeproj
xcode_scheme: TravisUITests
xcode_sdk: iphonesimulator12.1
osx_image: xcode10.1
language: swift
install:
  - rm Gemfile.lock
  - bundle install
addons:
  sauce_connect:
    username: "Jordan-Earnin"
    access_key: "8b775c04-d4da-475d-9fc8-6d4db6c8de7b"
env:
  - TEST_SUITE=TravisUITests/TravisUITests
  - TEST_SUITE=TravisUITests2/TravisUITests2
script:
  - set -o pipefail && xcodebuild -project "$TRAVIS_XCODE_PROJECT" -scheme "$TRAVIS_XCODE_SCHEME" -sdk "$TRAVIS_XCODE_SDK" -destination "platform=iOS Simulator,OS=latest,name=iPhone 7" test -only-testing:"$TEST_SUITE" | xcpretty
