xcode_project: Travis.xcodeproj
xcode_scheme: TravisUITests
xcode_sdk: iphonesimulator12.1
osx_image: xcode10.1
language: swift
install:
  - rm Gemfile.lock
  - bundle install
script:
  - fastlane hello
  - xcodebuild -project "$TRAVIS_XCODE_PROJECT" -scheme "$TRAVIS_XCODE_SCHEME" -sdk "$TRAVIS_XCODE_SDK" -destination "platform=iOS Simulator,OS=latest,name=iPhone 7" test-without-building -only-testing:TravisUITests/TravisUITests.swift
