xcode_workspace: Travis.xcodeproj
xcode_scheme: Travis
xcode_sdk: iphonesimulator12.1
osx_image: xcode10.1
language: objective-c
script:
   - xcodebuild clean test -project "$TRAVIS_XCODE_PROJECT" -scheme Travis -sdk "$TRAVIS_XCODE_SDK" -destination "platform=iOS Simulator,OS=latest,name=iPhone 7" CODE_SIGN_IDENTITY=“” CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet
