xcode_project: Travis.xcodeproj
xcode_scheme: Travis
xcode_sdk: iphonesimulator12.1
osx_image: xcode10.1
language: swift
env:
  - TEST_SUITE=TravisUITests
  - TEST_SUITE=TravisUITests2
script:
  - fastlane hello
  - fastlane scan --scheme "$TEST_SUITE"
